import { ThemeProvider } from "@/components/theme-provider"


import type { Metadata } from 'next'
import './globals.css'
import { Inter as FontSans } from "next/font/google"

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import { cn } from "@/lib/utils"
import Navbar from "@/components/navbar"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
        "min-h-screen bg-background m-0 p-0 font-sans antialiased",
        fontSans.variable
      )}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="dark:bg-[#191627] bg-[#FBFBFE]">
              <Navbar />
              {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
